version: 0.2

env:
  variables:
    TERRAFORM_VERSION: "1.5.5"
    TF_DIRECTORY: "terraform_code"
    TF_COMMAND: "plan"

phases:
  install:
    commands:
      # Usando a sintaxe ${VARIAVEL} para robustez
      - |
        echo "Detectando a arquitetura do sistema..."
        ARCH=$(uname -m)
        echo "Arquitetura detectada: ${ARCH}"

        case ${ARCH} in
          x86_64) TF_ARCH="amd64" ;;
          aarch64) TF_ARCH="arm64" ;;
          *) echo "Arquitetura não suportada: ${ARCH}"; exit 1 ;;
        esac

        echo "Arquitetura do Terraform a ser usada: ${TF_ARCH}"
        TF_FILENAME="terraform_${TERRAFORM_VERSION}_linux_${TF_ARCH}.zip"
        TF_URL="https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/${TF_FILENAME}"
        
        echo "Instalando dependências e o Terraform..."
        yum install -y unzip -q
        wget -q "${TF_URL}"
        unzip "${TF_FILENAME}"
        mv terraform /usr/local/bin/
        rm "${TF_FILENAME}"
        
        echo "Verificando a versão do Terraform..."
        terraform --version

  pre_build:
    commands:
      - |
        echo "Navegando para o diretório do Terraform: ${TF_DIRECTORY}"
        cd "${TF_DIRECTORY}"
        echo "Diretório de trabalho atual: $(pwd)"

  build:
    commands:
      - |
        echo "Inicializando o Terraform..."
        terraform init -reconfigure

        echo "Executando o comando Terraform: ${TF_COMMAND}"
        case ${TF_COMMAND} in
          plan)
            echo "Gerando o plano do Terraform..."
            terraform plan
            ;;
          apply)
            echo "Gerando o plano para aplicação..."
            terraform plan -out=tfplan
            echo "Aplicando as configurações do Terraform..."
            terraform apply -auto-approve tfplan
            ;;
          destroy)
            echo "Destruindo a infraestrutura..."
            terraform destroy -auto-approve
            ;;
          *)
            echo "Comando '${TF_COMMAND}' inválido. Use 'plan', 'apply' ou 'destroy'."
            exit 1
            ;;
        esac

  post_build:
    commands:
      - echo "Build para o comando '${TF_COMMAND}' concluído."
